name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install XVFB
      run: sudo apt-get install xvfb
    - name: Build with Ant
      run: ant jar
    - name: Run Unit Tests
      run: xvfb-run --auto-servernum ant test
